#!/usr/bin/env python3
"""
Human Kernel Stress Test

Expectations on Final Output:
    This stress test evaluates how the Tier 7 Human Kernel (Conscious Observer) processes
    a complex, open-ended research task and the expected quality and depth of its final answer.
    
    1. Single Entry Point Processing: 
       Given exactly one initial input signal (a raw string query simulating a human dropping a prompt),
       the Conscious Observer must ingest this signal, recognize its complexity, and autonomously 
       initiate a deep, multi-cycle OODA loop without requiring further prompting.
       
    2. Expected Answer Structure & Depth for the Cloud Competition Query:
       For the query "compare tech giant competition in US for cloud indstry, GCP, AWS, and Azure",
       the expected final output is NOT a shallow, single-paragraph summary. It should be a 
       highly structured, professional analysis generated by a "Senior Cloud Analyst" role.
       The answer should feature:
       - Executive Summary: High-level overview of the cloud market landscape in the US.
       - Market Share & Financials: Quantitative comparison of AWS, Azure, and GCP (revenue, growth rates).
       - Strategic Advantages: Deep dive into the unique selling propositions (USPs) of each provider 
         (e.g., AWS's first-mover advantage and vast services, Azure's enterprise integration and AI push, 
         GCP's data analytics and open-source strengths).
       - AI & Future Trends: How recent GenAI investments are reshaping their competition.
       - Conclusion/Recommendation: Synthesized final verdict based on the gathered evidence.
       
    3. Autonomous Evidence Gathering (Coping with Pressure):
       To write this detailed answer, the Kernel must autonomously formulate sub-queries, execute tools
       (like web search) via the MCP Host, extract atomic facts, and resolve contradictory information.
       It must handle failures or rate limits gracefully, managing its cognitive load without crashing.
       
    4. Quality Gate and Verifiability:
       The final synthesized report must pass the internal Quality Gate before being emitted.
       It must possess a high confidence score and provide a substantial Grounding Score by citing 
       real-world, up-to-date facts gathered during its execution cycles, ensuring the answer is 
       factual and free of hallucinations.

Usage:
    # Run via pytest
    python -m pytest tests/stress/human_stress_test.py -v -s --log-cli-level=DEBUG
    
    # Direct execution
    python tests/stress/human_stress_test.py
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import pytest

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from kernel.conscious_observer.engine import ConsciousObserver
from kernel.conscious_observer.types import ObserverPhase
from kernel.lifecycle_controller.types import SpawnRequest
from kernel.modality.types import RawInput
from shared.logging.main import get_logger

logger = get_logger(__name__)

# Single input query that pressures the human kernel
DEFAULT_STRESS_QUERY = "compare tech giant competition in US for cloud indstry, GCP, AWS, and Azure"


def pytest_addoption(parser):
    """Add custom pytest options for human stress tests."""
    # Ensure no conflict with stress_test.py if run globally
    try:
        parser.addoption(
            "--human-query",
            action="store",
            default=DEFAULT_STRESS_QUERY,
            help="Custom query string for the Human Kernel stress test",
        )
    except ValueError:
        pass


@pytest.fixture
def human_query(request):
    """Get custom query from command line."""
    return request.config.getoption("--human-query", default=DEFAULT_STRESS_QUERY)


@pytest.mark.stress
@pytest.mark.asyncio
async def test_human_kernel_stress(inference_kit, human_query):
    """
    Stress test for the Tier 7 Human Kernel.
    """
    query = human_query if human_query else DEFAULT_STRESS_QUERY
    logger.info("="*80)
    logger.info("🚀 INITIALIZING HUMAN KERNEL STRESS TEST")
    logger.info("="*80)
    
    start_time = time.time()
    
    # Instantiate the human kernel
    observer = ConsciousObserver(kit=inference_kit)
    
    # 1 Entrypoint: Ingest the raw string and let it figure out everything
    logger.info(f"📡 [ENTRYPOINT] Sending Signal: {query}")
    raw_input = RawInput(content=query)
    spawn_request = SpawnRequest(role="senior_cloud_analyst", objective=query)
    
    result = await observer.process(
        raw_input=raw_input,
        spawn_request=spawn_request
    )
    
    duration = time.time() - start_time
    
    # Assertions and Metric Extractions
    assert result.is_success, "The Human Kernel failed to complete the processing."
    
    obs_res = result.signals[0].body.get("data", {})
    
    logger.info("")
    logger.info("="*80)
    logger.info("📊 HUMAN KERNEL STRESS TEST RESULTS")
    logger.info("="*80)
    
    mode = obs_res.get('mode', 'UNKNOWN')
    final_phase = obs_res.get('final_phase', 'UNKNOWN')
    cycles = obs_res.get('total_cycles', 0)
    kernel_duration = obs_res.get('total_duration_ms', 0) / 1000.0
    
    logger.info(f"   [BRAIN DECISION] Mode Selected: {str(mode).upper()}")
    logger.info(f"   [BRAIN DECISION] Final Iteration Checkpoint: {str(final_phase).upper()}")
    logger.info(f"   [EXECUTION] OODA Cycles: {cycles}")
    logger.info(f"   [EXECUTION] Time Elapsed: {duration:.2f}s (Kernel: {kernel_duration:.2f}s)")
    
    if "salary" in query.lower():
        # Edge case test from original file: must be ESCALATED
        assert final_phase == ObserverPhase.ESCALATED, f"Expected ESCALATED due to security, got {final_phase}"
        logger.warning(f"⚠️ [SECURITY ESCALATION] Reason: {obs_res.get('partial_output', 'Rejected')}")
    else:
        assert final_phase == ObserverPhase.GATE_OUT, f"Expected GATE_OUT, but ended in {final_phase}"
        assert obs_res.get('filtered_output') is not None, "Did not receive filtered output."
        
        # Evaluate Quality Gate Metrics
        conf_score = obs_res.get('calibrated_confidence', {}).get('calibrated_confidence', 0.0)
        grounding = obs_res.get('grounding_report', {})
        grnd_score = grounding.get('grounding_score', 0.0) if grounding else 0.8
        total_claims = grounding.get('total_claims', 0) if grounding else 0
        
        logger.info(f"   [QUALITY GATE] Confidence Score: {conf_score:.2f}")
        logger.info(f"   [QUALITY GATE] Grounding Score: {grnd_score:.2f} (Claims: {total_claims})")
        
        output_content = obs_res['filtered_output'].get('content', 'NO CONTENT')
        
        print("\n" + "="*80)
        print("🎯 FINAL CONSCIOUS OUTPUT:")
        print("="*80)
        print(output_content)
        print("="*80 + "\n")
        
    logger.info("✅ STRESS TEST PASSED SUCCESSFULLY")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Human Kernel Stress Test")
    parser.add_argument("--query", "-q", type=str, default=DEFAULT_STRESS_QUERY, help="Custom query string")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    args, unknown = parser.parse_known_args()
    
    pytest_args = ["-v", "-s", __file__]
    if args.verbose:
        pytest_args.append("--log-cli-level=DEBUG")
    else:
        pytest_args.append("--log-cli-level=INFO")
        
    pytest_args.extend(["--human-query", args.query])
    
    sys.exit(pytest.main(pytest_args))
