import os

import pytest
from mcp.client.stdio import stdio_client

from tests.mcp.client_utils import SafeClientSession as ClientSession
from tests.mcp.client_utils import get_server_params


@pytest.mark.asyncio
async def test_docx_real_simulation():
    """
    REAL SIMULATION: Verify Docx Server (Create, Edit, Read).
    """
    params = get_server_params("docx_server", extra_dependencies=["python-docx", "pandas", "pillow"])

    doc_path = os.path.abspath("test_mcp_doc.docx")

    print("\n--- Starting Real-World Simulation: Docx Server ---")

    async with stdio_client(params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()

            # 1. Create Document
            print(f"1. Creating Document at {doc_path}...")
            await session.call_tool("create_document_file", arguments={"path": doc_path})

            # 2. Add Content
            print("2. Adding Content...")
            await session.call_tool("add_heading", arguments={"path": doc_path, "text": "Project Report", "level": 1})
            await session.call_tool("add_paragraph", arguments={"path": doc_path, "text": "This is an automated report generated by the Docx MCP server."})

            # 3. Add Table
            print("3. Adding Table...")
            await session.call_tool("add_table", arguments={"path": doc_path, "rows": 2, "cols": 2})
            await session.call_tool("set_cell_text", arguments={"path": doc_path, "table_index": 0, "row": 0, "col": 0, "text": "Metric"})
            await session.call_tool("set_cell_text", arguments={"path": doc_path, "table_index": 0, "row": 0, "col": 1, "text": "Value"})
            await session.call_tool("set_cell_text", arguments={"path": doc_path, "table_index": 0, "row": 1, "col": 0, "text": "Coverage"})
            await session.call_tool("set_cell_text", arguments={"path": doc_path, "table_index": 0, "row": 1, "col": 1, "text": "100%"})

            print("4. Verifying Content...")
            res = await session.call_tool("read_paragraphs", arguments={"path": doc_path})
            if not res.isError:
                print(f" \033[92m[PASS]\033[0m Paragraphs (Raw): {res.content[0].text}")
                # Try simple parsing if it looks like a list
                try:
                    import ast
                    paras = ast.literal_eval(res.content[0].text)
                    print(f" \033[92m[PASS]\033[0m Paragraph count: {len(paras)}")
                except:
                    print(" [WARN] Could not parse paragraph list")
            else:
                print(f" \033[91m[FAIL]\033[0m {res.content[0].text}")

            res = await session.call_tool("read_table", arguments={"path": doc_path, "table_index": 0})
            if not res.isError:
                print(f" \033[92m[PASS]\033[0m Table Data: {res.content[0].text}")

            # 5. Metadata
            print("5. Setting Metadata...")
            await session.call_tool("set_document_properties", arguments={"path": doc_path, "author": "Project Agent", "title": "Test Doc"})
            res = await session.call_tool("get_document_properties", arguments={"path": doc_path})
            print(f" \033[92m[PASS]\033[0m Props: {res.content[0].text}")

    # Cleanup
    if os.path.exists(doc_path):
        os.remove(doc_path)
        print(" \033[92m[PASS]\033[0m Cleanup")

    print("--- Docx Simulation Complete ---")

if __name__ == "__main__":
    import sys
    sys.exit(pytest.main(["-v", "-s", __file__]))
